CREATE TABLE Utilisateur(
   ID VARCHAR(10),
   NOM VARCHAR(30) NOT NULL,
   PRENOM VARCHAR(30) NOT NULL,
   SEXE VARCHAR(10) NOT NULL,
   TEL SMALLINT NOT NULL,
   MAIL VARCHAR(30) NOT NULL,
   PRIMARY KEY(ID)
);

CREATE TABLE Tuteur(
   IDparent VARCHAR(30),
   TYPE VARCHAR(15) NOT NULL,
   ID VARCHAR(10) NOT NULL,
   PRIMARY KEY(IDparent),
   UNIQUE(ID),
   FOREIGN KEY(ID) REFERENCES Utilisateur(ID)
);

CREATE TABLE Administrateur(
   IDadmin VARCHAR(15),
   ID VARCHAR(10) NOT NULL,
   PRIMARY KEY(IDadmin),
   UNIQUE(ID),
   FOREIGN KEY(ID) REFERENCES Utilisateur(ID)
);

CREATE TABLE Itineraire(
   IDitineraire VARCHAR(15),
   DEPART VARCHAR(20) NOT NULL,
   ARRIVEE VARCHAR(20) NOT NULL,
   DUREE SMALLINT NOT NULL,
   DISTANCE INT NOT NULL,
   PRIMARY KEY(IDitineraire)
);

CREATE TABLE Bus(
   IDbus VARCHAR(15),
   IMMATRICULATION VARCHAR(10) NOT NULL,
   CAPACITE INT NOT NULL,
   MARQUE VARCHAR(15) NOT NULL,
   LONGITUDE VARCHAR(15) NOT NULL,
   LATITUDE VARCHAR(15) NOT NULL,
   IDitineraire VARCHAR(15) NOT NULL,
   PRIMARY KEY(IDbus),
   FOREIGN KEY(IDitineraire) REFERENCES Itineraire(IDitineraire)
);

CREATE TABLE Arret(
   IDarret VARCHAR(15),
   NOMarret VARCHAR(20) NOT NULL,
   LONGarret VARCHAR(15) NOT NULL,
   LATarret VARCHAR(15) NOT NULL,
   IDbus VARCHAR(15) NOT NULL,
   PRIMARY KEY(IDarret),
   FOREIGN KEY(IDbus) REFERENCES Bus(IDbus)
);

CREATE TABLE Conducteur(
   IDconducteur VARCHAR(15),
   IDbus VARCHAR(15) NOT NULL,
   ID VARCHAR(10) NOT NULL,
   PRIMARY KEY(IDconducteur),
   UNIQUE(ID),
   FOREIGN KEY(IDbus) REFERENCES Bus(IDbus),
   FOREIGN KEY(ID) REFERENCES Utilisateur(ID)
);

CREATE TABLE Etudiant(
   IDetudiant VARCHAR(15),
   MATRICULE VARCHAR(15) NOT NULL,
   LOCALISATION VARCHAR(32) NOT NULL,
   IDarret VARCHAR(15) NOT NULL,
   ID VARCHAR(10) NOT NULL,
   PRIMARY KEY(IDetudiant),
   UNIQUE(ID),
   FOREIGN KEY(IDarret) REFERENCES Arret(IDarret),
   FOREIGN KEY(ID) REFERENCES Utilisateur(ID)
);

CREATE TABLE Scolariser(
   IDparent VARCHAR(30),
   IDetudiant VARCHAR(15),
   PRIMARY KEY(IDparent, IDetudiant),
   FOREIGN KEY(IDparent) REFERENCES Tuteur(IDparent),
   FOREIGN KEY(IDetudiant) REFERENCES Etudiant(IDetudiant)
);
